# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/api/room
Content-Type: application/json

{
  "name" : "test"
}

###

GET http://localhost:8080/api/room/1

###

GET http://localhost:8080/api/room/2

###

GET http://localhost:8080/api/userlog/1

###

POST http://localhost:8080/api/userlog
Content-Type:  application/json

{
  "chatRoomIdx": 1,
  "userName": "test"
}

###